version: '3.8'

services:
  app:
    image: speak-ai
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:YourStrongPassword@localhost:5432/speak
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PORT=5000
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=SpeakAI <noreply@speak-ai.xyz>
      - NODE_ENV=production
    network_mode: host
